# Generated by Django 4.2 on 2023-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_sign_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
