# Generated by Django 4.2 on 2023-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_sign_up_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='role',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
