# Generated by Django 4.2 on 2023-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_sign_up_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Acheteur', 'Acheteur'), ('Vendeur', 'Vendeur'), ('Vendeuse', 'Vendeuse')], max_length=100),
        ),
    ]
